feat:toast-notification
Jaynil1611/Javascript-Interview-Preparation pull request #6
Opened 2022-01-09 09:23 UTC by manmodesanket

## Description 
Toast notifications using vanilla js.

## Type
Machine Coding round.

## Related Technology
HTML, CSS, JavaScript.

## Source
I was asked this question in a interview. I was interviewing for Headout.

## Working Solution
Codesandbox link: https://codesandbox.io/s/toast-notification-h6cut

2022-01-14 07:17 UTC, Jaynil1611 requested changes
Please do the same as suggested in previous PR

2022-01-23 07:20 UTC, manmodesanket commented
Made changes as per PR review

2022-01-26 11:02 UTC, Jaynil1611 requested changes

2022-01-26 11:02 UTC, Jaynil1611 commented on vanillaJs/toast-notification/src/index.js
> +  let toastDiv = document.createElement("div");
Change `let` to `const`

2022-01-26 11:02 UTC, Jaynil1611 commented on vanillaJs/toast-notification/src/index.js
> +    let toastDivError = document.querySelector(".toast__notifications__error");
Change `let` to `const`

2022-01-26 11:02 UTC, Jaynil1611 commented on vanillaJs/toast-notification/src/index.js
> +    let mainToastDiv = document.querySelector(".toast__notifications");
Change `let` to `const`

2022-01-26 11:02 UTC, Jaynil1611 commented on vanillaJs/toast-notification/src/index.js
> +  let position = e.target.getAttribute("top");
Change `let` to `const`

2022-01-26 11:02 UTC, Jaynil1611 commented on vanillaJs/toast-notification/src/styles.css
> +    background-color: blue;
Change blue background to some light colour e.g. cyan

2022-02-09 05:56 UTC, Jaynil1611 requested changes

2022-02-09 05:56 UTC, Jaynil1611 commented on vanillaJs/toast-notification/README.md
> +Q. Upon clicking Button1 and Button2 toast notification should popup at the bottom of the screen and if Button3 is clicked error notification should popup at the top of screen.
Change button1 & button2, button3 as Info, Warning, Error in the problem description as well

2022-02-13 08:37 UTC, manmodesanket commented
@Jaynil1611 I have updated button names in README.md. Please have a look.

2022-02-13 16:02 UTC, Jaynil1611 approved these changes

2022-02-13 18:18 UTC, merged