feat:bubbling problem added
Jaynil1611/Javascript-Interview-Preparation pull request #7
Opened 2022-01-09 09:26 UTC by manmodesanket

## Description 
Bubbling Problem using react

## Type
Machine Coding Round

## Related Technology
React, css

## Source
Asked in Ridecell interview

## Working Solution
Codesandbox link: https://codesandbox.io/s/bubbling-problem-8erwc

2022-01-14 07:15 UTC, Jaynil1611 requested changes
The bubbling problem name seems very vague
Give a more descriptive problem name

2022-01-14 07:15 UTC, Jaynil1611 commented on react-problems/bubbling-problem/public/index.html
> +<!DOCTYPE html>
Remove index.html

2022-01-14 07:15 UTC, Jaynil1611 commented on react-problems/bubbling-problem/src/App.js
> +import "./styles.css";
Keep this file & add this file & readme as a folder under
`react-snippets`

2022-01-14 07:15 UTC, Jaynil1611 commented on react-problems/bubbling-problem/src/index.js
> +import { StrictMode } from "react";
Remove this file

2022-01-14 07:15 UTC, Jaynil1611 commented on react-problems/bubbling-problem/src/styles.css
> +.App {
Remove this file

2022-01-14 07:15 UTC, Jaynil1611 commented on react-problems/bubbling-problem/README.md
> +
Add ##Solution as a heading & then add the link
Change the title from `CodeSandbox Link` to `<question-name> Solution` & add the link under the whole title

2022-01-23 07:17 UTC, manmodesanket commented
Made changes as per the request.

2022-01-26 10:49 UTC, Jaynil1611 approved these changes
@manmodesanket Change the sandbox name to `Event Delegation` as well

2022-01-27 07:54 UTC, merged